### ISSUE TITLE
Backend For EdNet

### ISSUE THREAD

**Issue by himanshuramoliya** [vishwashah29/Group8_Educational_Networking_Tool#21]
A backend for site to store various data and to verify credentials for login

**Comment by VismayTandel** [comment]
First made a three different schema question, answer, project with necessary attributes. Then For Project Forum and Discussion Forum, I made an endpoint for saving the data and retrieving the data from the MongoDB cloud storage.
Backend Github repo : https://github.com/VismayTandel/SE_Backend

**Comment by Shafest** [comment]
for backend purpose we needed to have 4 different schemas namely user, answers, question and project, out of which I made user schema for the purpose of the users, in user I have identified necessary attributes that should be present for important use, i.e. admin code, professor code. Now front end create account page requires info of users and login page requires to validate the details, for such issues I have created some endpoints for login, register after combining the whole work we have deployed it on heroku : https://ednet.herokuapp.com/
